# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tJb1N45ctrN1cq-7mU-qzIrMg0UrBlB4
"""

# 1 - Faça um programa que mostre a mensagem "alo mundo" na tela

print("Alo mundo!")

# 2 - Faça um programa que peça um numero e então mostre a mengagem o numero informaod foi [número].

valor = input("Enter a number ")
resultado = "O numero selecionado é: {}".format(valor)
print(resultado)

# 3 - Faça um programa que peça dois numero e imprima a soma

valor = float(input("insira seu primeiro numero: "))
valor2 = float(input("insira seu segundo numero: "))

resultadoSoma = valor + valor2
print("Esse é o resultado da soma:", resultadoSoma)

# 4 - Faça um programa que peça as 4 notas bimestrais e mostre a média

primeiraNota = float(input("insira a sua primeira nota do bimestre: "))
segundaNota = float(input("insira a sua segunda nota do bimestre: "))
terceiraNota = float(input("insira a sua terceira nota do bimestre: "))
quartaNota = float(input("insira a sua quarta nota do bimestre: "))


calcSoma = (primeiraNota + segundaNota + terceiraNota + quartaNota) / 2
print(calcSoma)

# 5 - Faça um programa que converta metros para centímetros

metroUser = float(input("Insira seu metro: "))
convertCM = metroUser * 100
print("O valor em centimetros é", convertCM)

# 6 - Faça um programa que peça o raio de um circulo, calcule e mostre a área

import math

raiodoCirculo = float(input("Insira o numero do raio:" ))
resultado = math.pi * (raiodoCirculo ** 2)

print("Esse é o resultado da área:", resultado)

# 7 - Faça um Programa que calcule a área de um quadrado, em seguida mostre o dobro desta área para o usuário.

valorQuadrado = float(input('Insira o valor do lado:' ))
calcLados = valorQuadrado * valorQuadrado

print("O dobro da área é:", calcLados)

# 8 - Faça um programa que pergunte quanto você ganha por hora e o numero de horas trabalhadas nesse mes, calcule e mostre o total de salario no referido mes

valorHora = float(input("Insira valor da sua hora: "))
horasTrabalhadas = float(input("Insira as horas trabalhadas: "))

totalSalario = valorHora * horasTrabalhadas

print('Total de salario no referido mes: ', totalSalario)

# 9 - Faça um programa que peça a temperatura em graus Farenheit, transforme e mostre a temperatura em graus Celsius

farenheit = float(input('insira a temperatura em graus farenheit para converter em celsius: '))

calcFaren = (farenheit - 32) / 1.8
resultadoConversao = calcFaren

print('Esse é a temperatura em celsius: ', resultadoConversao)

# 10 - Faça um programa que peça a temperatura em graus Celsius transforme e mostre em graus fahrenheit

celsius = float(input('insira temperatura celsius para conversao em farenheit: '))

calcCelsius = (celsius * 1.8) + 32
resultadoCelsius = calcCelsius

print('Essa é a temperatura em Farenheit: ', resultadoCelsius)

# 11 - Faça um programa que peça 2 números inteiros e um número real. calcule e mostre:
# a. produto do dobro do primeiro com metade do segundo
# b. a soma do triplo do primeiro com terceiro
# c. o terceiro elevado ao cubo

numeroInteiro = int(input('insira seu numero inteiro: '))
numeroInteiro2 = int(input('insira seu numero inteiro: '))
numeroReal = float(input('Insira seu numero real: '))

print ('A:', ((2*numeroInteiro) * (numeroInteiro/2)))
print ('B:', (3 * numeroInteiro) + numeroReal)
print ('C:', numeroReal**3)

# 12 - Tendo dados de entrada a altura de uma pessoa, construe um algoritmo que calcule o seu peso ideal, usando a seguinte formula: (72.7*altura) - 58

altura = float(input('Altura: '))
print('peso ideal: ', 72.7*altura - 58)

# # 13 - Tendo dado de entrada a altura (h) de uma pessoa, construa um algortimo que calcule seu peso ideal, utilizando as seguinte fórmulas:
# a. para homens: (72.7*h) - 58
# b. para mulheres: (62.1*h) - 44.7

sexo = int(input('Selecione opção 1 se for do sexo Masculino / Selecione opção 2 se for do sexo feminino: '))
h = float(input('Altura:'))
peso = float(input('Peso:'))

peso_ideal = (72.7*h) - 58 if sexo == 1 else (62.1*h) - 44.7

if peso < peso_ideal:
	print('Abaixo do peso ideal!')
elif peso == peso_ideal:
	print('Dentro do peso ideal!')
else:
	print('Acima do peso ideal!')


print ('Peso: %.2f / Peso ideal: %.2f' %(peso, peso_ideal))

# # 14 - joao papo de pescador, homem de bem, comprou um microcomputador para controlar o rendimento diário de seu trabalho.
# toda vez que ele traz um peso de peixes maior que o estabelecido pelo regulamento depescado estadode são paulo (50 quilos)
# deve pagar uma multa de 4 reais por quilo excedente. joao precisa que você faça um programa que leia a variavel peso (peso de peixes) e calcule o excesso.
# gravar na variavel excesso a quantidade de quilos alem do limite e na variavel multa o valor da multa que joao deverá pagar.
# imprima os dados do programa com as mensagem adequadas.


peso = float(input('Insira o seu peso: '))
if peso > 50:
    excesso = peso - 50
    multa = excesso * 4
else:
    excesso = 0
    multa = 0

print("Peso: {}".format(peso))
print('Excesso: {}'.format(excesso))
print('Multa: {}'.format(multa))

# 15) Faça um Programa que pergunte quanto você ganha por hora e o número de horas trabalhadas no mês. Calcule e mostre o total do seu salário no referido mês,
# sabendo-se que são descontados 11% para o Imposto de Renda, 8% para o INSS e 5% para o sindicato, faça um programa que nos dê:

# a) salário bruto.
# b) quanto pagou ao INSS.
# c) quanto pagou ao sindicato.
# d) o salário líquido.
# e) calcule os descontos e o salário líquido, conforme a tabela abaixo:

# + Salário Bruto : R$
# - IR (11%) : R$
# - INSS (8%) : R$
# - Sindicato ( 5%) : R$
# = Salário Liquido : R$

# Obs.: Salário Bruto - Descontos = Salário Líquido.

hora = float(input('Quanto você ganha por hora: '))
qntdHoras = float(input('Insira sua quantidade de horas trabalhadas: '))

salario_bruto = hora * qntdHoras
inss, sindicato, IR = 0.08 * salario_bruto, 0.05 * salario_bruto, 0.11 * salario_bruto
salarioLiquido = salario_bruto - inss - sindicato - IR

print('Salário Bruto:', salario_bruto)
print('INSS:', inss)
print('Sindicato:', sindicato)
print('IR:', IR)
print('Salário Liquido:', salarioLiquido)

# 16 - Faça um programa para uma loja de tintas. O programa deverá pedir o tamanho em metros quadrados da área a ser pintada. Considere que a
# cobertura da tinta é de 1 litro para cada 3 metros quadrados e que a tinta é vendida em latas de 18 litros, que custam R$ 80,00.
# Informe ao usuário as quantidades de latas de tinta a serem compradas e o preço total.

metros = int(input('Metros: '))

if metros % 54 != 0:
    latas = int(metros / 54) + 1
else:
    latas = int(metros / 54)

valor = latas * 80

print('Uma lata está custando por', valor)

# 17 -  Faça um Programa para uma loja de tintas. O programa deverá pedir o tamanho em metros quadrados da área a ser pintada. Considere que a cobertura da tinta é de 1 litro
# para cada 6 metros quadrados e que a tinta é vendida em latas de 18 litros, que custam R$ 80,00 ou em galões de 3,6 litros, que custam R$ 25,00. Informe ao usuário as quantidades de tinta a
# serem compradas e os respectivos preços em 3 situações: comprar apenas latas de 18 litros; comprar apenas galões de 3,6 litros; misturar latas e galões, de forma que o desperdício de tinta seja menor.
# Acrescente 10% de folga e sempre arredonde os valores para cima, isto é, considere latas cheias.

import math

litros_lata = 18
preco_lata = 80
litros_galao = 3.6
preco_galao = 25

m2 = float(input("Por favor, insira o tamanho da área em metros quadrados: "))
litros_necessarios = m2 / 6

qtd_latas = math.ceil(litros_necessarios / litros_lata)
custo_latas = qtd_latas * preco_lata
qtd_galoes = math.ceil(litros_necessarios / litros_galao)
custo_galoes = qtd_galoes * preco_galao

print("Somente latas de 18L:")
print(f'O cliente precisa comprar {qtd_latas} latas, que custarão R${custo_latas}.')

print("Somente galões de 3.6L:")
print(f'O cliente precisa comprar {qtd_galoes} galões, que custarão R${custo_galoes}.')

litros_necessarios_folga = litros_necessarios * 1.1
qtd_latas_c, qtd_galoes_c = 0, 0

if litros_necessarios_folga >= litros_lata:
    qtd_latas_c = int(litros_necessarios_folga / litros_lata)
    litros_necessarios_folga -= qtd_latas_c * litros_lata

if litros_necessarios_folga > 0:
    qtd_galoes_c = math.ceil(litros_necessarios_folga / litros_galao)

custo_mix = (qtd_latas_c * preco_lata) + (qtd_galoes_c * preco_galao)

print("Mix de latas e galões:")
print(f'O cliente precisa comprar {qtd_latas_c} latas e {qtd_galoes_c} galões, que custarão R${custo_mix}.')

# 18 - Faça um programa que peça o tamanho de um arquivo para download (em MB) e a velocidade de um link de Internet (em Mbps),
# calcule e informe o tempo aproximado de download do arquivo usando este link (em minutos).

tamanhoMB = float(input('Tamanho do arquivo MB: '))
velocidadeMBPS = float(input('Velocidade da internet'))

calc = (tamanhoMB / velocidadeMBPS) * 60

print('Esse é o tempo aproximado de download do arquivo: ', calc)